name: ray_environment
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py39h06a4308_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.3=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.0.20=0
  - libcurand=10.3.5.119=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py39h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.13=h7f8727e_0
  - pillow=10.2.0=py39h5eee18b_0
  - pip=23.3.1=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - pytorch=2.1.2=py3.9_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_1
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.1.2=py39_cu118
  - torchtriton=2.1.0=py39
  - torchvision=0.16.2=py39_cu118
  - typing_extensions=4.9.0=py39h06a4308_1
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.3
      - aiohttp-cors==0.7.0
      - aiorwlock==1.4.0
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - blessed==1.20.0
      - cachetools==5.3.3
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorful==0.5.6
      - deprecated==1.2.14
      - distlib==0.3.8
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - farama-notifications==0.0.4
      - fastapi==0.108.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-api-core==2.17.1
      - google-auth==2.29.0
      - googleapis-common-protos==1.63.0
      - gpustat==1.1.1
      - gputil==1.4.0
      - grpcio==1.62.1
      - gymnasium==0.28.1
      - h11==0.14.0
      - httptools==0.6.1
      - idna==3.6
      - imageio==2.34.0
      - importlib-metadata==6.11.0
      - jax-jumpy==1.0.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - lazy-loader==0.3
      - lz4==4.3.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - msgpack==1.0.8
      - multidict==6.0.5
      - networkx==3.2.1
      - nvidia-ml-py==12.535.133
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - openpyxl==3.1.2
      - opentelemetry-api==1.23.0
      - opentelemetry-exporter-otlp==1.23.0
      - opentelemetry-exporter-otlp-proto-common==1.23.0
      - opentelemetry-exporter-otlp-proto-grpc==1.23.0
      - opentelemetry-exporter-otlp-proto-http==1.23.0
      - opentelemetry-proto==1.23.0
      - opentelemetry-sdk==1.23.0
      - opentelemetry-semantic-conventions==0.44b0
      - packaging==24.0
      - pandas==2.2.1
      - platformdirs==4.2.0
      - prometheus-client==0.20.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - py-spy==0.3.14
      - pyarrow==15.0.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pygments==2.17.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.1
      - ray==2.9.3
      - ray-cpp==2.9.3
      - referencing==0.34.0
      - rich==13.7.1
      - rpds-py==0.18.0
      - rsa==4.9
      - scikit-image==0.22.0
      - scipy==1.12.0
      - sentry-sdk==2.7.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smart-open==7.0.3
      - smmap==5.0.1
      - sniffio==1.3.1
      - starlette==0.32.0.post1
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tifffile==2024.2.12
      - typer==0.9.0
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - uvloop==0.19.0
      - virtualenv==20.25.1
      - wandb==0.17.3
      - watchfiles==0.21.0
      - wcwidth==0.2.13
      - websockets==12.0
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.18.1
prefix: /work/cmcc/jg24923/miniconda3/envs/ray_3
